stages:
  - publish


variables:
  DOCKER_REGISTRY: <ECR_REPO_URL>
  AWS_DEFAULT_REGION: us-east-1
  APP_NAME: streamlit-app
  DOCKER_HOST: tcp://docker:2375



publish:
  stage: publish
  image:
    name: ubuntu:latest
  script:
    - sudo apt-get update
    - sudo apt-get -y install awscli docker.io
    - sudo docker --version
    - sudo aws --version
    - sudo aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - sudo aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - sudo aws configure set region $AWS_DEFAULT_REGION
    - sudo $(aws ecr get-login --no-include-email | sed 's|https://||') && sudo docker login -u AWS -p $(aws ecr get-login-password | sed 's|AWS\ \-\-password\-stdin\ ||') $DOCKER_REGISTRY
    - sudo docker build -t $DOCKER_REGISTRY/$APP_NAME:$CI_PIPELINE_IID .
    - sudo docker push $DOCKER_REGISTRY/$APP_NAME:$CI_PIPELINE_IID
    - echo "push is FINSHED"